### ISSUE TITLE
Html-check-frag-mode freezes Emacs

### ISSUE THREAD

**Issue by ReneFroger** [TobiasZawada/html-check-frag#4]
Hi there! Thanks for sharing this package! 

However, I was unable to use it.

This is my configuration:

(use-package html-check-frag
  :config
  (add-hook 'html-mode-hook (lambda () (html-check-frag-mode 1)))
  (add-hook 'web-mode-hook (lambda () (html-check-frag-mode 1)))
  )

When I open a HTML-file, Emacs freezes and is unusable.
When I remove the hook to `html-check-frag-mode`, then open the HTML-file again,
and do <kbd>M-x</kbd> `html-check-frag-mode`, Emacs freezes again.

I'm using Emacs 25.0.50 on Ubuntu 15.10.

**Comment by TobiasZawada** [comment]
I have just installed [emacs 25.1.50.2](https://launchpad.net/~ubuntu-elisp/+archive/ubuntu/ppa), started it with `emacs -Q` and tried `M-x html-check-frag-mode` on a file `/tmp/test.html` with the content listed below. I also closed the file, added `(lambda () (html-check-frag-mode 1))` to `html-mode-hook`, and loaded the file again. Everything is working as expected. Note, that I am generally using Ubuntu 14.04 where emacs 24.3.1 is my normal working horse.

Thus, we have more work to hunt down the bug... As a first step can you retry with `emacs -Q` and with the html-file content below?

``` html
<!DOCTYPE html>
<html>
  <head>
    <title>
      Checking <t>html-check-frag</t>
    </title>
  </head>
  <body>
    <h1>Header one</h1>
    This file exists only for checking <t>html-check-frag</t>.
    Looks like <t>html-check-frag</t> works well with <t>emacs-25-1-20</t>.
    <p>
      <img src="html-check-frag.png">
    </p>
  </body>
</html>
```

EDIT: I had also the chance to test emacs 25.0.50.1 (64bit mingw-build) on a larger HTML-file. Same result. Everything works like expected.

**Comment by Wilfred** [comment]
@ReneFroger are you using html-mode or web-mode when it hangs?

**Comment by ReneFroger** [comment]
Both.

**Comment by ReneFroger** [comment]
It hangs in both modes.

**Comment by ReneFroger** [comment]
It hangs in both modes.

**Comment by ReneFroger** [comment]
It hangs in both modes.

**Comment by ReneFroger** [comment]
It hangs in both modes.

**Comment by ReneFroger** [comment]
It hangs in both modes.

**Comment by ReneFroger** [comment]
It hangs in both modes.

**Comment by TobiasZawada** [comment]
@ReneFroger Does it also hang with `emacs -Q`, only loading `html-mode` as well as `html-check-frag` and editing the example in my comment 3 days ago?

I assume that this is a conflict with some other package you are using.
When we find the conflicting package maybe I am able to fix the problem.

**Comment by ReneFroger** [comment]
You're right. I tested it with `emacs -Q` and the problem don't occur.

It occurs only when I use `html-check-frag` in pair with Web-mode, a very
popular package for editing html pages, [more info here](http://web-mode.org/).

You can test it with the following configuration, I assume you're known with the
[use-package](https://github.com/jwiegley/use-package)?

```
(use-package web-mode

    :mode
    "\\.phtml\\'" 
    "\\.html\\'" 
    "\\.tpl\\.php\\'" 
    "\\.[agj]sp\\'" 
    "\\.as[cp]x\\'" 
    "\\.erb\\'" 
    "\\.mustache\\'" 
    "\\.djhtml\\'")



(use-package html-check-frag

    :config
    (add-hook 'html-mode-hook (lambda () (html-check-frag-mode 1)))
    (add-hook 'web-mode-hook (lambda () (html-check-frag-mode 1)))
    )
```

**Comment by TobiasZawada** [comment]
First insight: `web-mode` sets the variable `forward-sexp-function` to `web-mode-forward-sexp` which does really strange things. It interprets the full html file as one sexp. Letting `forward-sexp-function` to `nil` in `html-check-frag-region` partially solves this problem. But if one corrects mismatching html tags they are not re-fontified.

This requires some deeper digging...

**Comment by ReneFroger** [comment]
From what I know, web-mode had some conflicts with other packages in the past. @fxbois knows a lot about the inner working of `web-mode-forward-sexp`, so he could perhaps tell you why this is causing a crash.

**Comment by TobiasZawada** [comment]
@ReneFroger Could you please try the [web branch version](https://github.com/TobiasZawada/html-check-frag/blob/web/html-check-frag.el)?
Note, that I can reproduce some problem with web-mode but not the freezing of emacs.
If your emacs still freezes with the branch "web" could you switch on Debugging on Quit and give a back-trace. Could you attach an example for reconstruction of the freezing?
Thanks in advance,
Tobias Zawada

**Comment by ReneFroger** [comment]
Tobias, thanks for your reply and sorry for the delay, I will come back on this in the weekend!

**Comment by ReneFroger** [comment]
I tried the web branch version. Now Emacs is not crashing anymore, but the html-check-frag is not always highlighting the mismatched tags.

But that's an another thing which I can live with it, the web branch version seems to answer my original issue. Thanks for that! Are you considering to use it as the default code? If so, then I could upgrade it with MELPA.

**Comment by TobiasZawada** [comment]
The web branch is merged with master. The bug fix should be in MELPA after the next update of the archive. This should happen on 2016-01-31, 12:00 GME.
Best regards, Tobias

**Comment by ReneFroger** [comment]
After updating html-check-frag, and adding a hook to web-mode with html-check-frag, after opening a HTML file, my Emacs freezes again. So unfortunately, it seems we have still the same bug.

I also noticed the memory of Emacs instance is growing fast. Propably there is a never ending loop somewhere in the conflict between `web-mode` and `html-check-frag`.

I had the same issue with web-mode [here](http://emacs.stackexchange.com/questions/13074/why-is-autoheader-crashing-with-web-mode).

**Comment by TobiasZawada** [comment]
Dear Rene,
please send me a minimal html file where this error occurs with emacs 
-Q, loading web-mode and html-check-frag.
Thanks in advance.

Best regards,
Tobias

**Comment by ReneFroger** [comment]
If you don't have this issue, then it's probably related with my configuration. I will it figure it out soon.

Thanks for looking on it, by the way!
